name: Multimodal_mazes
channels:
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - ipykernel
  - python-graphviz
  - graphviz
  - plotly
  - scikit-learn
  - networkx
  - tqdm
  - seaborn
  - pytorch
  - shap
  - pip
  - pip:
    - netgraph
    - neat-python
# prefix: C:\Users\ad04\AppData\Local\miniconda3\envs\Multimodal_mazes
prefix: /Users/alexd/anaconda3/envs/RNN_Mecp2